### PR TITLE
Building Web Applications with Python course - Structure

### PR DESCRIPTION
**Pull request by thejeshgn**
- [x]  Added course details
- [x] Added chapter descriptions
- [x] Added lessons descriptions

### CODE REVIEW

**Comment by thejeshgn** [comment]
@anandology just initial work.

**Comment by anandology** [comment]
Thanks @thejeshgn. Could you please create an issue as well to make it easier to discuss about the course?

**Comment by thejeshgn** [comment]
@anandology here https://github.com/fossunited/monschool-website/issues/27

**Comment by anandology** [comment]
The name of the file should be `course.yml` instead of `course.yaml`. @thejeshgn could you please fix it?

**Comment by thejeshgn** [comment]
Done.

**Review by anandology — APPROVED** [review]
LGTM!

**Pull request merged**
