### PR TITLE
Add course outline for Git & GitHub for beginners

### PR DESCRIPTION
**Pull request by HarshCasper**
Issue #36

### CODE REVIEW

**Comment by anandology** [comment]
I'm looking at all the chapter heading together...

```
Version Control System & Git
Getting Started with Git
Git & GitHub
Contributing using Git & GitHub
Open Source
```

I feel there is some room for improvement here.  What do you think of changing them to:

```
Introduction to Git
Getting Started with Git
Collaborative Development using Git
The GitHub Flow
Contributing to Open Source Projects
```

or

```
Introduction
Getting Started
Collaborative Development
The GitHub Flow
Contributing to Open Source Projects
```

@de-sh and @nikochiko do you have any suggestions here?

**Comment by nikochiko** [comment]
As this course is meant to be from a non-technical perspective (not only developers), I feel some of the course content (internal objects, collaboration with other developers, contributing to open source) may not be relevant for non-developers.
One solution could be to explicitly identify these sections as slightly technical or meant only for better understanding Git.

**Comment by HarshCasper** [comment]
Hi @anandology 

I have implemented all your suggestions. Please have a look 😄

**Review by anandology — APPROVED** [review]
LGTM!

**Pull request merged**
