### PR TITLE
Add chapters for Mypy Primer

### PR DESCRIPTION
**Pull request by tusharsadhwani**
Currently only contains the description, chapter and lesson names.

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
@anandology PTAL, what's the next step?

**Comment by anandology** [comment]
Can you suggest an image for the course? I'll add that and publish the course as a preview on mon.school.

**Comment by tusharsadhwani** [comment]
I like the stock mypy image:

mypy 1

**Comment by tusharsadhwani** [comment]
Here's the svg
https://camo.githubusercontent.com/20e0f72b4f84dc5b42aceb95eb8eaa6c574746c0057e9e2525dd6cb4797d565f/687474703a2f2f6d7970792d6c616e672e6f72672f7374617469632f6d7970795f6c696768742e737667

**Pull request merged**
